name: Build_global

on:
  push:
    branches:
      - master # Change this to your default branché

  workflow_dispatch:
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: gradle_build
      - uses: gradle/gradle-build-action@v2
          with:
            arguments: build
